version: '3.5'

services:
  mariadb:
    container_name: tabi_mariadb
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /data/mariadb
    networks:
      - tabi
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: tabi_phpmyadmin
    image: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8081:80"
    networks:
      - tabi

  postgres:
    container_name: tabi_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-212121}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - tabi
    restart: unless-stopped
  
  pgadmin:
    container_name: tabi_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-212121}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - tabi
    restart: unless-stopped
  
  biserver:
    container_name: tabi_biserver
    #build: ./biserver/
    image: dgraselli/pentaho-biserver:9.0
    ports:
      - "${BISERVER_PORT:-8080}:8080"
    networks:
      - tabi
    restart: unless-stopped

networks:
  tabi:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    mariadb:
